stages:
  - build
  - deploy

build website:
  stage: build
  image: node:18
  script:
    - npm install
    - npm run build
  artifacts:
    paths:
      - dist/nft-app

deploy angular:
  stage: deploy
  image:
    name: pockost/phploy:4.9.3
    entrypoint: [""]
  script:
    - phploy -s prod