stages:
  - build
  - deploy

build de la partie client:
  image: node:18
  stage: build
  script:
    - npm install --production
    - npm run build
  artifacts:
    paths:
      - dist/nft-app/

deploiement de la partie client:
  image: 
    name: pockost/phploy:4.9.3
    entrypoint: [""]
  stage: deploy
  script:
    - phploy -s client-prod
